name: clubber
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_ui_toolkit: ^0.0.3+8
  jiffy: ^4.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  fonts:
    - family: PulpDisplay
      fonts:
        - asset: lib/fonts/PulpDisplay-Light.ttf
          weight: 300
        - asset: lib/fonts/PulpDisplay-Regular.ttf
          weight: 500
        - asset: lib/fonts/PulpDidsplay-Bold.ttf
          weight: 700
        - asset: lib/fonts/PulpDisplay-ExtraBold.ttf
          weight: 900
