name: clubbers_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  clubber:
    path: ../clubber
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: PulpDisplay
      fonts:
        - asset: ../clubber/fonts/PulpDisplay-Light.ttf
          weight: 300
        - asset: ../clubber/fonts/PulpDisplay-Regular.ttf
          weight: 500
        - asset: ../clubber/fonts/PulpDisplay-Bold.ttf
          weight: 700
        - asset: ../clubber/fonts/PulpDisplay-ExtraBold.ttf
          weight: 900
